package co.edu.ubosque.logic;
// Generated 10 nov. 2020 19:47:43 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PerfilUsuario generated by hbm2java
 */
@Entity
@Table(name = "PerfilUsuario", schema = "dbo", catalog = "teemplea")
public class PerfilUsuario implements java.io.Serializable {

	private Integer id;
	private String nombre;

	public PerfilUsuario() {
	}

	public PerfilUsuario(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
