package co.edu.ubosque.model;
// Generated 29 nov. 2020 18:26:13 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "Empresa", schema = "dbo", catalog = "teemplea")
public class Empresa implements java.io.Serializable {

	private Integer id;
	private String nombreEmpresa;
	private int rut;
	private long telefono;
	private String correo;
	private String desripcion;
	private String departamento;
	private String direccion;
	private String tipoCompañia;
	private String sector;
	private String pagina;
	private String nombres;
	private String apellidos;
	private String cargo;
	private long telefonoMovil;
	private long telefonoFijo;

	public Empresa() {
	}

	public Empresa(String nombreEmpresa, int rut, long telefono, String correo, String desripcion, String departamento,
			String direccion, String tipoCompañia, String sector, String pagina, String nombres, String apellidos,
			String cargo, long telefonoMovil, long telefonoFijo) {
		this.nombreEmpresa = nombreEmpresa;
		this.rut = rut;
		this.telefono = telefono;
		this.correo = correo;
		this.desripcion = desripcion;
		this.departamento = departamento;
		this.direccion = direccion;
		this.tipoCompañia = tipoCompañia;
		this.sector = sector;
		this.pagina = pagina;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.cargo = cargo;
		this.telefonoMovil = telefonoMovil;
		this.telefonoFijo = telefonoFijo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombreEmpresa", nullable = false, length = 50)
	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	@Column(name = "rut", nullable = false)
	public int getRut() {
		return this.rut;
	}

	public void setRut(int rut) {
		this.rut = rut;
	}

	@Column(name = "telefono", nullable = false, precision = 18, scale = 0)
	public long getTelefono() {
		return this.telefono;
	}

	public void setTelefono(long telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo", nullable = false, length = 50)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "desripcion", nullable = false, length = 50)
	public String getDesripcion() {
		return this.desripcion;
	}

	public void setDesripcion(String desripcion) {
		this.desripcion = desripcion;
	}

	@Column(name = "departamento", nullable = false, length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "tipoCompañia", nullable = false, length = 50)
	public String getTipoCompañia() {
		return this.tipoCompañia;
	}

	public void setTipoCompañia(String tipoCompañia) {
		this.tipoCompañia = tipoCompañia;
	}

	@Column(name = "sector", nullable = false, length = 50)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "pagina", nullable = false, length = 50)
	public String getPagina() {
		return this.pagina;
	}

	public void setPagina(String pagina) {
		this.pagina = pagina;
	}

	@Column(name = "nombres", nullable = false, length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false, length = 50)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "cargo", nullable = false, length = 50)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "telefonoMovil", nullable = false, precision = 18, scale = 0)
	public long getTelefonoMovil() {
		return this.telefonoMovil;
	}

	public void setTelefonoMovil(long telefonoMovil) {
		this.telefonoMovil = telefonoMovil;
	}

	@Column(name = "telefonoFijo", nullable = false, precision = 18, scale = 0)
	public long getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(long telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

}
