package co.edu.ubosque.model;
// Generated 23/11/2020, 10:27:51 p. m. by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExperienciaLaboral generated by hbm2java
 */
@Entity
@Table(name = "ExperienciaLaboral", schema = "dbo", catalog = "teemplea")
public class ExperienciaLaboral implements java.io.Serializable {

	private Integer id;
	private int identificacion;
	private String empresa;
	private String sector;
	private String cargo;
	private String funciones;
	private Date fechainicial;
	private Date fechafinal;

	public ExperienciaLaboral() {
	}

	public ExperienciaLaboral(int identificacion, String empresa, String sector, String cargo, String funciones) {
		this.identificacion = identificacion;
		this.empresa = empresa;
		this.sector = sector;
		this.cargo = cargo;
		this.funciones = funciones;
	}

	public ExperienciaLaboral(int identificacion, String empresa, String sector, String cargo, String funciones,
			Date fechainicial, Date fechafinal) {
		this.identificacion = identificacion;
		this.empresa = empresa;
		this.sector = sector;
		this.cargo = cargo;
		this.funciones = funciones;
		this.fechainicial = fechainicial;
		this.fechafinal = fechafinal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "identificacion", nullable = false)
	public int getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(int identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "empresa", nullable = false, length = 50)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "sector", nullable = false, length = 50)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "cargo", nullable = false, length = 50)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "funciones", nullable = false, length = 200)
	public String getFunciones() {
		return this.funciones;
	}

	public void setFunciones(String funciones) {
		this.funciones = funciones;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainicial", length = 10)
	public Date getFechainicial() {
		return this.fechainicial;
	}

	public void setFechainicial(Date fechainicial) {
		this.fechainicial = fechainicial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafinal", length = 10)
	public Date getFechafinal() {
		return this.fechafinal;
	}

	public void setFechafinal(Date fechafinal) {
		this.fechafinal = fechafinal;
	}

}
