package co.edu.ubosque.model;
// Generated 23/11/2020, 10:27:51 p. m. by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InformacionPersonal generated by hbm2java
 */
@Entity
@Table(name = "informacionPersonal", schema = "dbo", catalog = "teemplea")
public class InformacionPersonal implements java.io.Serializable {

	private Integer id;
	private long identificacion;
	private String nombres;
	private String apellidos;
	private Date fechaNacimiento;
	private String lugarNacimiento;
	private String direccion;
	private long telefono;
	private String estadoCivil;
	private String correo;
	private String descripcion;
	private String genero;

	public InformacionPersonal() {
	}

	public InformacionPersonal(long identificacion, String nombres, String apellidos, Date fechaNacimiento,
			String lugarNacimiento, String direccion, long telefono, String estadoCivil, String correo, String genero) {
		this.identificacion = identificacion;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.estadoCivil = estadoCivil;
		this.correo = correo;
		this.genero = genero;
	}

	public InformacionPersonal(long identificacion, String nombres, String apellidos, Date fechaNacimiento,
			String lugarNacimiento, String direccion, long telefono, String estadoCivil, String correo, String descripcion,
			String genero) {
		this.identificacion = identificacion;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.estadoCivil = estadoCivil;
		this.correo = correo;
		this.descripcion = descripcion;
		this.genero = genero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "identificacion", nullable = false, precision = 18, scale = 0)
	public long getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(long identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "nombres", nullable = false, length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false, length = 50)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "lugarNacimiento", nullable = false, length = 50)
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false, precision = 18, scale = 0)
	public long getTelefono() {
		return this.telefono;
	}

	public void setTelefono(long telefono) {
		this.telefono = telefono;
	}

	@Column(name = "estadoCivil", nullable = false, length = 50)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "correo", nullable = false, length = 50)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "genero", nullable = false, length = 50)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

}
