package co.edu.ubosque.model;
// Generated 23/11/2020, 10:27:51 p. m. by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InformacionAcademica generated by hbm2java
 */
@Entity
@Table(name = "InformacionAcademica", schema = "dbo", catalog = "teemplea")
public class InformacionAcademica implements java.io.Serializable {

	private Integer id;
	private int identificacion;
	private String universidad;
	private String titulo;
	private String nivelEstudios;
	private Date fechaInicial;
	private Date fechaFinal;

	public InformacionAcademica() {
	}

	public InformacionAcademica(int identificacion, String universidad, String titulo, String nivelEstudios) {
		this.identificacion = identificacion;
		this.universidad = universidad;
		this.titulo = titulo;
		this.nivelEstudios = nivelEstudios;
	}

	public InformacionAcademica(int identificacion, String universidad, String titulo, String nivelEstudios,
			Date fechaInicial, Date fechaFinal) {
		this.identificacion = identificacion;
		this.universidad = universidad;
		this.titulo = titulo;
		this.nivelEstudios = nivelEstudios;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "identificacion", nullable = false)
	public int getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(int identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "universidad", nullable = false, length = 50)
	public String getUniversidad() {
		return this.universidad;
	}

	public void setUniversidad(String universidad) {
		this.universidad = universidad;
	}

	@Column(name = "titulo", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "nivelEstudios", nullable = false, length = 50)
	public String getNivelEstudios() {
		return this.nivelEstudios;
	}

	public void setNivelEstudios(String nivelEstudios) {
		this.nivelEstudios = nivelEstudios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicial", length = 10)
	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFinal", length = 10)
	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

}
