package co.edu.ubosque.model;
// Generated 30 nov. 2020 19:32:45 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OfertaLaboral generated by hbm2java
 */
@Entity
@Table(name = "OfertaLaboral", schema = "dbo", catalog = "teemplea")
public class OfertaLaboral implements java.io.Serializable {

	private Integer id;
	private String titulo;
	private String desripcion;
	private String destacado;
	private String departamento;
	private String categoria;
	private long salario;
	private String detalles;
	private String nombreEmpresa;
	private String cargo;
	private Date fecha;

	public OfertaLaboral() {
	}

	public OfertaLaboral(String titulo, String desripcion, String destacado, String departamento, String categoria,
			long salario, String detalles, String cargo, Date fecha) {
		this.titulo = titulo;
		this.desripcion = desripcion;
		this.destacado = destacado;
		this.departamento = departamento;
		this.categoria = categoria;
		this.salario = salario;
		this.detalles = detalles;
		this.cargo = cargo;
		this.fecha = fecha;
	}

	public OfertaLaboral(String titulo, String desripcion, String destacado, String departamento, String categoria,
			long salario, String detalles, String nombreEmpresa, String cargo, Date fecha) {
		this.titulo = titulo;
		this.desripcion = desripcion;
		this.destacado = destacado;
		this.departamento = departamento;
		this.categoria = categoria;
		this.salario = salario;
		this.detalles = detalles;
		this.nombreEmpresa = nombreEmpresa;
		this.cargo = cargo;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "titulo", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "desripcion", nullable = false, length = 100)
	public String getDesripcion() {
		return this.desripcion;
	}

	public void setDesripcion(String desripcion) {
		this.desripcion = desripcion;
	}

	@Column(name = "destacado", nullable = false, length = 100)
	public String getDestacado() {
		return this.destacado;
	}

	public void setDestacado(String destacado) {
		this.destacado = destacado;
	}

	@Column(name = "departamento", nullable = false, length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "categoria", nullable = false, length = 50)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "salario", nullable = false, precision = 18, scale = 0)
	public long getSalario() {
		return this.salario;
	}

	public void setSalario(long salario) {
		this.salario = salario;
	}

	@Column(name = "detalles", nullable = false, length = 500)
	public String getDetalles() {
		return this.detalles;
	}

	public void setDetalles(String detalles) {
		this.detalles = detalles;
	}

	@Column(name = "nombreEmpresa", length = 500)
	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	@Column(name = "cargo", nullable = false, length = 500)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
