package co.edu.ubosque.model;
// Generated 1/12/2020, 4:04:58 p. m. by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoReferencia generated by hbm2java
 */
@Entity
@Table(name = "tipoReferencia", schema = "dbo", catalog = "teemplea")
public class TipoReferencia implements java.io.Serializable {

	private Integer id;
	private String sigla;
	private String nombre;

	public TipoReferencia() {
	}

	public TipoReferencia(String sigla, String nombre) {
		this.sigla = sigla;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sigla", nullable = false, length = 50)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
