package co.edu.ubosque.model;
// Generated 23/11/2020, 10:27:51 p. m. by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "TipoDocumento", schema = "dbo", catalog = "teemplea")
public class TipoDocumento implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String sigla;
	private Set<CrearCuenta> crearCuentas = new HashSet<CrearCuenta>(0);

	public TipoDocumento() {
	}

	public TipoDocumento(String nombre, String sigla) {
		this.nombre = nombre;
		this.sigla = sigla;
	}

	public TipoDocumento(String nombre, String sigla, Set<CrearCuenta> crearCuentas) {
		this.nombre = nombre;
		this.sigla = sigla;
		this.crearCuentas = crearCuentas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "SIGLA", nullable = false, length = 5)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<CrearCuenta> getCrearCuentas() {
		return this.crearCuentas;
	}

	public void setCrearCuentas(Set<CrearCuenta> crearCuentas) {
		this.crearCuentas = crearCuentas;
	}

}
